POST https://api-v3.igdb.com/platforms
user-key: f13f3ae70c0329eaf198249bba188dbd


fields *; where category = 5; limit 300;

###

# Genesis Button
POST https://api-v3.igdb.com/games
user-key: f13f3ae70c0329eaf198249bba188dbd


fields name,summary,rating; where platforms = 4 ; sort popularity desc; limit 50;

###

POST https://api-v3.igdb.com/search
user-key: f13f3ae70c0329eaf198249bba188dbd


fields *; search "sonic the hedgehog"; limit 50;